### ISSUE TITLE
Edge Transit PvE Rangefinder Perk

### ISSUE THREAD

**Issue by treetop24** [rafigalbur/DIM-Wishlists#1]
## Expected Behavior

Per the Forsaken PvE tab in pandapaxxy's Destiny 2 Weapons Breakdown spreadsheet and [their original post in r/sharditkeepit](https://old.reddit.com/r/sharditkeepit/comments/9fot1q/grenade_launcher_god_rolls) Rangefinder is a Tier 1 recommended perk for Edge Transit, auto-loading holster is not.

## Actual Behavior

In the PvE text file, Tier 1 perk recommendations for Edge Transit are Threat Detector and Auto-Loading Holster, rather than Threat Detector and Rangefinder.

**Comment by rafigalb** [comment]
Thanks! Pushed fix for it.

**Comment by treetop24** [comment]
You're a rockstar! I was working on a PR but you beat me to it. Thanks for all the work you put in!

**Comment by rafigalb** [comment]
Honestly there are probably a bunch more inconsistencies so let me know if you find any more!
